#!/bin/bash
# Helper script to determine if nginx repo is present in /etc/apt/sources.list
SOURCES=/etc/apt/sources.list
grep -qi nginx $SOURCES
if [[ $? -ne 0 ]]
then
  echo -e "\n# Nginx repo\ndeb http://nginx.org/packages/debian/ squeeze nginx\ndeb-src http://nginx.org/packages/debian/ squeeze nginx" >> $SOURCES
  # Add the nginx keys
  wget http://nginx.org/packages/keys/nginx_signing.key -O /tmp/nginx_signing.key
  cat /tmp/nginx_signing.key | apt-key add -
fi
